//
// Created by dela on 08/07/23.
//

#ifndef LAB_PROGRAMMAZIONE_DIALOGALLACTIVITY_H
#define LAB_PROGRAMMAZIONE_DIALOGALLACTIVITY_H


class DialogAllActivity {

};


#endif //LAB_PROGRAMMAZIONE_DIALOGALLACTIVITY_H
